/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/dashboard.invoices.index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard.clients.index'
import { Route as DashboardInvoicesCreateRouteImport } from './routes/dashboard.invoices.create'
import { Route as DashboardInvoicesEditIdRouteImport } from './routes/dashboard.invoices.edit.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesCreateRoute = DashboardInvoicesCreateRouteImport.update({
  id: '/invoices/create',
  path: '/invoices/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesEditIdRoute = DashboardInvoicesEditIdRouteImport.update({
  id: '/invoices/edit/$id',
  path: '/invoices/edit/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/invoices/create': typeof DashboardInvoicesCreateRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/invoices/edit/$id': typeof DashboardInvoicesEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/invoices/create': typeof DashboardInvoicesCreateRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/invoices/edit/$id': typeof DashboardInvoicesEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/invoices/create': typeof DashboardInvoicesCreateRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/invoices/edit/$id': typeof DashboardInvoicesEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/pay/$invoiceId'
    | '/dashboard/'
    | '/dashboard/invoices/create'
    | '/dashboard/clients/'
    | '/dashboard/invoices/'
    | '/dashboard/invoices/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/pay/$invoiceId'
    | '/dashboard'
    | '/dashboard/invoices/create'
    | '/dashboard/clients'
    | '/dashboard/invoices'
    | '/dashboard/invoices/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/pay/$invoiceId'
    | '/dashboard/'
    | '/dashboard/invoices/create'
    | '/dashboard/clients/'
    | '/dashboard/invoices/'
    | '/dashboard/invoices/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices/': {
      id: '/dashboard/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices/create': {
      id: '/dashboard/invoices/create'
      path: '/invoices/create'
      fullPath: '/dashboard/invoices/create'
      preLoaderRoute: typeof DashboardInvoicesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices/edit/$id': {
      id: '/dashboard/invoices/edit/$id'
      path: '/invoices/edit/$id'
      fullPath: '/dashboard/invoices/edit/$id'
      preLoaderRoute: typeof DashboardInvoicesEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInvoicesCreateRoute: typeof DashboardInvoicesCreateRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
  DashboardInvoicesEditIdRoute: typeof DashboardInvoicesEditIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInvoicesCreateRoute: DashboardInvoicesCreateRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  DashboardInvoicesEditIdRoute: DashboardInvoicesEditIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
